oSearchData = {
"ayuda":  [ ["SeccionAyuda.html","Sección Ayuda",2] , ["SeccionReportes.html","Sección Reportes",2] , ["SeccionHerramientas.html","Sección Herramientas",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionSalir.html","Sección Salir",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"sistema":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",9] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",3] , ["IngresodelSistema.html","Ingreso del Sistema",3] , ["SeccionAyuda.html","Sección Ayuda",2] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",2] , ["SeccionHerramientas.html","Sección Herramientas",1] , ["SeccionSalir.html","Sección Salir",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"adquirente":  [ ["PantalladeConsulta.html","Pantalla de Consulta",4] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",4] , ["SeccionReportes.html","Sección Reportes",3] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",2] , ["SeccionHerramientas.html","Sección Herramientas",1] , ["SeccionSalir.html","Sección Salir",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"carnet":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",4] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",2] , ["SeccionHerramientas.html","Sección Herramientas",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionSalir.html","Sección Salir",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["SeccionReportes.html","Sección Reportes",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"sac":  [ ["SeccionHerramientas.html","Sección Herramientas",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionSalir.html","Sección Salir",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"requerimientos":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",3] ] ,
"hardware":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] ] ,
"software":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] ] ,
"cliente":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] ] ,
"web":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",3] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"acceso":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"mediante":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"navegador":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",3] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"internet":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",2] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] ] ,
"para":  [ ["SeccionReportes.html","Sección Reportes",5] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",3] , ["PantalladeConsulta.html","Pantalla de Consulta",3] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",3] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"obtener":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"óptimos":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"resultados":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"requiere":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"equipo":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"con":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] , ["SeccionReportes.html","Sección Reportes",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"capacidad":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"correr":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] ] ,
"alguno":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"los":  [ ["PantalladeConsulta.html","Pantalla de Consulta",7] , ["SeccionReportes.html","Sección Reportes",6] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",4] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] , ["ImpresiondeReportes.html","Impresión de Reportes",2] , ["SeccionAyuda.html","Sección Ayuda",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"navegadores":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"soportados":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"cuales":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"detallan":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"continuación":  [ ["SeccionReportes.html","Sección Reportes",2] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"operativo":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"versión":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"windows":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",3] ] ,
"vista":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",3] ] ,
"2003":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",4] ] ,
"explorer":  [ ["PantalladeConsulta.html","Pantalla de Consulta",3] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"sp2":  [ ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"firefox":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",6] ] ,
"safari":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] ] ,
"apple":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] ] ,
"macos":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] ] ,
"linux":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",4] ] ,
"redhat":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"rhel":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"opensuse":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"ubuntu":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"fedora":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"son":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"necesarios":  [ ["SeccionReportes.html","Sección Reportes",2] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"eficiencia":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"preferencia":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"del":  [ ["SeccionReportes.html","Sección Reportes",4] , ["IngresodelSistema.html","Ingreso del Sistema",3] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] , ["SeccionAyuda.html","Sección Ayuda",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"usuario":  [ ["IngresodelSistema.html","Ingreso del Sistema",7] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] , ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"organización":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"debe":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"considerar":  [ ["SeccionReportes.html","Sección Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"que":  [ ["SeccionReportes.html","Sección Reportes",5] , ["ExportarunReporte.html","Exportar un Reporte",5] , ["PantalladeConsulta.html","Pantalla de Consulta",5] , ["IngresodelSistema.html","Ingreso del Sistema",5] , ["ImpresiondeReportes.html","Impresión de Reportes",3] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",3] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] ] ,
"tales":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"dependen":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"cantidad":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"aplicaciones":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"simultáneas":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"utiliza":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"trabajo":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"caso":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"configuración":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"mínima":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"requerida":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"recomendada":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"arquitectura":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"32bits":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"64bits":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"procesador":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"intel":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"pentium":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] ] ,
"ghz":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"sup":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"memoria":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"512mb":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"1gb":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"microsoft":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"office":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",2] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"2007":  [ ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"copyright":  [ ["SeccionHerramientas.html","Sección Herramientas",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionSalir.html","Sección Salir",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"2010":  [ ["SeccionHerramientas.html","Sección Herramientas",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionSalir.html","Sección Salir",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"wellcom":  [ ["SeccionHerramientas.html","Sección Herramientas",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionSalir.html","Sección Salir",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"created":  [ ["SeccionHerramientas.html","Sección Herramientas",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionSalir.html","Sección Salir",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"with":  [ ["SeccionHerramientas.html","Sección Herramientas",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionSalir.html","Sección Salir",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"the":  [ ["SeccionHerramientas.html","Sección Herramientas",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionSalir.html","Sección Salir",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"freeware":  [ ["SeccionHerramientas.html","Sección Herramientas",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionSalir.html","Sección Salir",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"edition":  [ ["SeccionHerramientas.html","Sección Herramientas",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionSalir.html","Sección Salir",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"helpndoc":  [ ["SeccionHerramientas.html","Sección Herramientas",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionSalir.html","Sección Salir",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"free":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"html":  [ ["SeccionReportes.html","Sección Reportes",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"help":  [ ["SeccionHerramientas.html","Sección Herramientas",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionSalir.html","Sección Salir",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"documentation":  [ ["SeccionAyuda.html","Sección Ayuda",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] ] ,
"generator":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionAyuda.html","Sección Ayuda",1] , ["SeccionSalir.html","Sección Salir",1] , ["RequerimientosdeHardwareySoftw.html","Requerimientos de Hardware y Software SAC2",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"buen":  [ ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"funcionamiento":  [ ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"reportes":  [ ["SeccionReportes.html","Sección Reportes",6] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"necesario":  [ ["PantalladeConsulta.html","Pantalla de Consulta",3] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"instalen":  [ ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"barras":  [ ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"permitan":  [ ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"popup":  [ ["ConfiguracionNavegador.html","Configuración Navegador de Internet",2] ] ,
"por":  [ ["ExportarunReporte.html","Exportar un Reporte",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"ejemplo":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionReportes.html","Sección Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"superior":  [ ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"deshabilite":  [ ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"opción":  [ ["SeccionReportes.html","Sección Reportes",2] , ["SeccionAyuda.html","Sección Ayuda",1] , ["SeccionSalir.html","Sección Salir",1] , ["SeccionHerramientas.html","Sección Herramientas",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"permita":  [ ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"single":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionReportes.html","Sección Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"source":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionReportes.html","Sección Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"chm":  [ ["SeccionAyuda.html","Sección Ayuda",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"pdf":  [ ["ImpresiondeReportes.html","Impresión de Reportes",2] , ["SeccionHerramientas.html","Sección Herramientas",1] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] , ["SeccionReportes.html","Sección Reportes",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"doc":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionReportes.html","Sección Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"and":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionReportes.html","Sección Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"creation":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionReportes.html","Sección Reportes",1] , ["ConfiguracionNavegador.html","Configuración Navegador de Internet",1] ] ,
"iii":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"ingreso":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"pantalla":  [ ["SeccionReportes.html","Sección Reportes",5] , ["PantalladeConsulta.html","Pantalla de Consulta",4] , ["IngresodelSistema.html","Ingreso del Sistema",3] , ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"autenticación":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"como":  [ ["IngresodelSistema.html","Ingreso del Sistema",2] , ["SeccionAyuda.html","Sección Ayuda",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"muestra":  [ ["SeccionReportes.html","Sección Reportes",3] , ["IngresodelSistema.html","Ingreso del Sistema",3] , ["ImpresiondeReportes.html","Impresión de Reportes",2] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"siguiente":  [ ["IngresodelSistema.html","Ingreso del Sistema",4] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"imagen":  [ ["IngresodelSistema.html","Ingreso del Sistema",3] ] ,
"aquí":  [ ["IngresodelSistema.html","Ingreso del Sistema",2] ] ,
"donde":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"poder":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"acceder":  [ ["IngresodelSistema.html","Ingreso del Sistema",2] , ["SeccionHerramientas.html","Sección Herramientas",1] ] ,
"aplicación":  [ ["SeccionSalir.html","Sección Salir",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"tendrá":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"tener":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"asignado":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"contraseña":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"realizara":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"acciones":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"introducir":  [ ["IngresodelSistema.html","Ingreso del Sistema",2] , ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"nombre":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] , ["SeccionReportes.html","Sección Reportes",2] , ["IngresodelSistema.html","Ingreso del Sistema",2] , ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"password":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"dar":  [ ["ExportarunReporte.html","Exportar un Reporte",2] , ["SeccionReportes.html","Sección Reportes",2] , ["IngresodelSistema.html","Ingreso del Sistema",2] , ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"clic":  [ ["ImpresiondeReportes.html","Impresión de Reportes",2] , ["PantalladeConsulta.html","Pantalla de Consulta",2] , ["ExportarunReporte.html","Exportar un Reporte",2] , ["IngresodelSistema.html","Ingreso del Sistema",2] , ["SeccionReportes.html","Sección Reportes",2] ] ,
"botón":  [ ["SeccionReportes.html","Sección Reportes",2] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"login":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"una":  [ ["SeccionReportes.html","Sección Reportes",9] , ["PantalladeConsulta.html","Pantalla de Consulta",5] , ["IngresodelSistema.html","Ingreso del Sistema",3] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"vez":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"ingrese":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"inicial":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"dando":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"bienvenida":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"denotando":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"menú":  [ ["IngresodelSistema.html","Ingreso del Sistema",3] ] ,
"función":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"consiste":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"seleccione":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"las":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] , ["IngresodelSistema.html","Ingreso del Sistema",2] ] ,
"opciones":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] , ["IngresodelSistema.html","Ingreso del Sistema",2] , ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"elegir":  [ ["SeccionReportes.html","Sección Reportes",4] , ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"esta":  [ ["SeccionAyuda.html","Sección Ayuda",1] , ["SeccionSalir.html","Sección Salir",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] , ["SeccionHerramientas.html","Sección Herramientas",1] ] ,
"dividido":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"secciones":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"muestran":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"cada":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"puede":  [ ["ExportarunReporte.html","Exportar un Reporte",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"través":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"ella":  [ ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"full":  [ ["SeccionSalir.html","Sección Salir",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"featured":  [ ["SeccionSalir.html","Sección Salir",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"multi":  [ ["SeccionSalir.html","Sección Salir",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"format":  [ ["SeccionSalir.html","Sección Salir",1] , ["IngresodelSistema.html","Ingreso del Sistema",1] ] ,
"sección":  [ ["SeccionAyuda.html","Sección Ayuda",1] , ["SeccionSalir.html","Sección Salir",1] , ["SeccionReportes.html","Sección Reportes",1] , ["SeccionHerramientas.html","Sección Herramientas",1] ] ,
"mostrará":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"lista":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"pantallas":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"consultar":  [ ["SeccionAyuda.html","Sección Ayuda",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"operación":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",6] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"procesos":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"día":  [ ["SeccionReportes.html","Sección Reportes",2] ] ,
"presenta":  [ ["SeccionReportes.html","Sección Reportes",2] ] ,
"posibilidad":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"generar":  [ ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"reporte":  [ ["SeccionReportes.html","Sección Reportes",14] , ["ImpresiondeReportes.html","Impresión de Reportes",3] , ["ExportarunReporte.html","Exportar un Reporte",2] ] ,
"consulta":  [ ["PantalladeConsulta.html","Pantalla de Consulta",8] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"monitoreo":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"cifras":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",5] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"control":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"liquidación":  [ ["SeccionReportes.html","Sección Reportes",2] ] ,
"dólares":  [ ["SeccionReportes.html","Sección Reportes",2] ] ,
"integración":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"respuestas":  [ ["SeccionAyuda.html","Sección Ayuda",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"intercambio":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"bancos":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"socios":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"transacciones":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"extemporáneas":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"promociones":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"mastercard":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"visa":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"interfases":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"prepago":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"dará":  [ ["SeccionReportes.html","Sección Reportes",2] , ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"descripción":  [ ["SeccionReportes.html","Sección Reportes",4] , ["PantalladeConsulta.html","Pantalla de Consulta",2] ] ,
"detallada":  [ ["SeccionReportes.html","Sección Reportes",2] , ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"genérica":  [ ["SeccionReportes.html","Sección Reportes",2] , ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"componentes":  [ ["SeccionReportes.html","Sección Reportes",3] , ["PantalladeConsulta.html","Pantalla de Consulta",2] ] ,
"conforman":  [ ["SeccionReportes.html","Sección Reportes",2] , ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"componente":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"fecha":  [ ["SeccionReportes.html","Sección Reportes",4] , ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"inicio":  [ ["SeccionReportes.html","Sección Reportes",2] ] ,
"icono":  [ ["SeccionReportes.html","Sección Reportes",3] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"despliega":  [ ["SeccionReportes.html","Sección Reportes",2] ] ,
"calendario":  [ ["SeccionReportes.html","Sección Reportes",2] ] ,
"seleccionar":  [ ["SeccionReportes.html","Sección Reportes",5] , ["PantalladeConsulta.html","Pantalla de Consulta",4] ] ,
"fin":  [ ["SeccionReportes.html","Sección Reportes",2] ] ,
"número":  [ ["PantalladeConsulta.html","Pantalla de Consulta",6] , ["SeccionReportes.html","Sección Reportes",2] ] ,
"transacción":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] , ["SeccionReportes.html","Sección Reportes",2] ] ,
"permite":  [ ["PantalladeConsulta.html","Pantalla de Consulta",8] , ["SeccionReportes.html","Sección Reportes",7] , ["SeccionSalir.html","Sección Salir",1] ] ,
"tipo":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"banco":  [ ["PantalladeConsulta.html","Pantalla de Consulta",6] , ["SeccionReportes.html","Sección Reportes",4] ] ,
"adquirientes":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"emisor":  [ ["PantalladeConsulta.html","Pantalla de Consulta",3] , ["SeccionReportes.html","Sección Reportes",2] ] ,
"fuente":  [ ["SeccionReportes.html","Sección Reportes",2] ] ,
"interés":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"mostrar":  [ ["SeccionReportes.html","Sección Reportes",3] , ["PantalladeConsulta.html","Pantalla de Consulta",2] ] ,
"datos":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"archivo":  [ ["ImpresiondeReportes.html","Impresión de Reportes",2] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionReportes.html","Sección Reportes",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"seleccionó":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"presentarlo":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"parámetros":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"presionar":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"nueva":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"ventana":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionReportes.html","Sección Reportes",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"pop":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"ups":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"barra":  [ ["SeccionReportes.html","Sección Reportes",2] , ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"herramientas":  [ ["SeccionReportes.html","Sección Reportes",2] , ["SeccionAyuda.html","Sección Ayuda",1] , ["SeccionHerramientas.html","Sección Herramientas",1] ] ,
"procesando":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"indicador":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"proceso":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"entrar":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"Índice":  [ ["SeccionReportes.html","Sección Reportes",2] ] ,
"todo":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"este":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"dado":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"alta":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"convenga":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"exportar":  [ ["SeccionReportes.html","Sección Reportes",2] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"cualquiera":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"formatos":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"existentes":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"imprimir":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"imprime":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"seleccionado":  [ ["ExportarunReporte.html","Exportar un Reporte",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"num":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"paginas":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"páginas":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"paginado":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"cambiar":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"página":  [ ["PantalladeConsulta.html","Pantalla de Consulta",4] , ["SeccionReportes.html","Sección Reportes",2] ] ,
"page":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["SeccionReportes.html","Sección Reportes",1] ] ,
"específica":  [ ["SeccionReportes.html","Sección Reportes",1] ] ,
"abrirá":  [ ["ImpresiondeReportes.html","Impresión de Reportes",2] , ["ExportarunReporte.html","Exportar un Reporte",2] , ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"formato":  [ ["ImpresiondeReportes.html","Impresión de Reportes",3] , ["ExportarunReporte.html","Exportar un Reporte",3] ] ,
"desee":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"nota":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"dependiendo":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"maneje":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"aparecer":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"cuadro":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"advertencia":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"haciendo":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"referencia":  [ ["PantalladeConsulta.html","Pantalla de Consulta",3] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"diferente":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"cual":  [ ["SeccionAyuda.html","Sección Ayuda",1] , ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"elija":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"yes":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"sin":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"problemas":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"haya":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"excel":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"word":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"power":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"point":  [ ["ExportarunReporte.html","Exportar un Reporte",1] ] ,
"impresión":  [ ["ImpresiondeReportes.html","Impresión de Reportes",4] , ["PantalladeConsulta.html","Pantalla de Consulta",2] ] ,
"tipos":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"ajuste":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"auto":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"ajusta":  [ ["ImpresiondeReportes.html","Impresión de Reportes",3] ] ,
"tamaño":  [ ["ImpresiondeReportes.html","Impresión de Reportes",2] ] ,
"acuerdo":  [ ["ImpresiondeReportes.html","Impresión de Reportes",2] ] ,
"actual":  [ ["ImpresiondeReportes.html","Impresión de Reportes",2] ] ,
"size":  [ ["ImpresiondeReportes.html","Impresión de Reportes",2] ] ,
"tal":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"fit":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"whole":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"definidos":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"easily":  [ ["SeccionHerramientas.html","Sección Herramientas",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"create":  [ ["SeccionHerramientas.html","Sección Herramientas",1] , ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"sites":  [ ["ImpresiondeReportes.html","Impresión de Reportes",1] ] ,
"solicitados":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"esperados":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"aparecerán":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"misma":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"podrá":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"explotar":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"información":  [ ["SeccionAyuda.html","Sección Ayuda",2] , ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] , ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"mostrada":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"mes":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"año":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"dato":  [ ["PantalladeConsulta.html","Pantalla de Consulta",5] ] ,
"obligatorio":  [ ["PantalladeConsulta.html","Pantalla de Consulta",5] ] ,
"sino":  [ ["PantalladeConsulta.html","Pantalla de Consulta",4] ] ,
"selecciona":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] ] ,
"cuenta":  [ ["PantalladeConsulta.html","Pantalla de Consulta",3] ] ,
"ingresar":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] ] ,
"captura":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] ] ,
"realizada":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"configurar":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] ] ,
"aparezca":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"dirección":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"url":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] ] ,
"esto":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"realice":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"siguientes":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"pasos":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] ] ,
"tenga":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"pueden":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"variar":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"solo":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"ubicar":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"encabezado":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] ] ,
"pie":  [ ["PantalladeConsulta.html","Pantalla de Consulta",2] ] ,
"bien":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"dentro":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"realizar":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"mismos":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"borrar":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"contenido":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"recuadros":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"están":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"blanco":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"damos":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"aceptar":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"terminar":  [ ["PantalladeConsulta.html","Pantalla de Consulta",1] ] ,
"podremos":  [ ["SeccionHerramientas.html","Sección Herramientas",1] ] ,
"módulo":  [ ["SeccionHerramientas.html","Sección Herramientas",1] ] ,
"reintegros":  [ ["SeccionHerramientas.html","Sección Herramientas",1] ] ,
"documents":  [ ["SeccionHerramientas.html","Sección Herramientas",1] ] ,
"podemos":  [ ["SeccionAyuda.html","Sección Ayuda",1] ] ,
"encontrar":  [ ["SeccionAyuda.html","Sección Ayuda",1] ] ,
"referente":  [ ["SeccionAyuda.html","Sección Ayuda",2] ] ,
"tema":  [ ["SeccionAyuda.html","Sección Ayuda",1] ] ,
"específico":  [ ["SeccionAyuda.html","Sección Ayuda",1] ] ,
"necesite":  [ ["SeccionAyuda.html","Sección Ayuda",1] ] ,
"así":  [ ["SeccionAyuda.html","Sección Ayuda",1] ] ,
"sugerencias":  [ ["SeccionAyuda.html","Sección Ayuda",1] ] ,
"condiciones":  [ ["SeccionAyuda.html","Sección Ayuda",1] ] ,
"uso":  [ ["SeccionAyuda.html","Sección Ayuda",1] ] ,
"otra":  [ ["SeccionAyuda.html","Sección Ayuda",1] ] ,
"soporte":  [ ["SeccionAyuda.html","Sección Ayuda",1] ] ,
"módulos":  [ ["SeccionAyuda.html","Sección Ayuda",1] ] ,
"vii":  [ ["SeccionSalir.html","Sección Salir",1] ] ,
"salir":  [ ["SeccionSalir.html","Sección Salir",1] ] ,
"cerrar":  [ ["SeccionSalir.html","Sección Salir",1] ] ,
"manera":  [ ["SeccionSalir.html","Sección Salir",1] ] ,
"adecuada":  [ ["SeccionSalir.html","Sección Salir",1] ] ,
"viii":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"matriz":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"escalamiento":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"centro":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"comando":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"nivel":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] ] ,
"business":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] ] ,
"champion":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] ] ,
"teléfono":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] ] ,
"celular":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] ] ,
"correo":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] ] ,
"electrónico":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] ] ,
"imelda":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"gonzález":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"ejecución":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"planes":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"instalación":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"contingencia":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"ext":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",14] ] ,
"1538":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"044":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",11] ] ,
"gonzalez":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"prosa":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",17] ] ,
"com":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",16] ] ,
"moisés":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] ] ,
"romero":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",6] ] ,
"coordinación":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"proyecto":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] ] ,
"sac2":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",7] ] ,
"7748":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] ] ,
"moises":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] ] ,
"rosario":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"vargas":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"validación":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",5] ] ,
"compensadas":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",5] ] ,
"3261":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"maria":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"sandra":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"tanguma":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"meléndez":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"3219":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"pilar":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"gómez":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"aburto":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"3160":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"gomez":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"yasmín":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"ornelas":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"valet":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"yasmin":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"emma":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"ramírez":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"granados":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"capacitación":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"clientes":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"ramirez":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"verónica":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"puente":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] ] ,
"domínguez":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"recopilación":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"3286":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"veronica":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"mariza":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"lópez":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"estevez":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"internacional":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"3269":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"lopez":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"rosa":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"isela":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"corona":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"cruz":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"interredes":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"facturación":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"extemporánea":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"3388":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"yesica":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"cuellar":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"flores":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"local":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"circuito":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"global":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"3386":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"paola":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"pérez":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"jaimes":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"integral":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"compensación":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"pos":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"perez":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"responsable":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",3] ] ,
"7775":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"vpuented":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"operativos":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"Álvaro":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"ontiveros":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",2] ] ,
"unidad":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"negocios":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"sistemas":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"7725":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ] ,
"alvaro":  [ ["MatrizdeEscalamiento.html","Matriz de Escalamiento",1] ]
}